// <auto-generated />
namespace SeleniumExcelAddIn
{
    partial class Ribbon1 : Microsoft.Office.Tools.Ribbon.RibbonBase
    {
        /// <summary>
        /// デザイナー変数が必要です。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        public Ribbon1()
            : base(Globals.Factory.GetRibbonFactory())
        {
            InitializeComponent();
        }

        /// <summary> 
        /// 使用中のリソースをすべてクリーンアップします。
        /// </summary>
        /// <param testDataWorksheetName="disposing">マネージ リソースを破棄する場合は true を指定し、その他の場合は false を指定します。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region コンポーネント デザイナーで生成されたコード

        /// <summary>
        /// デザイナーのサポートに必要なメソッドです。
        /// このメソッドの内容をコード エディターで変更しないでください。
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.tab1 = this.Factory.CreateRibbonTab();
            this.mainGroup = this.Factory.CreateRibbonGroup();
            this.toggleListPaneVisibleButton = this.Factory.CreateRibbonToggleButton();
            this.createScenarioButton = this.Factory.CreateRibbonButton();
            this.createTestDataButton = this.Factory.CreateRibbonButton();
            this.syntaxCheckButton = this.Factory.CreateRibbonButton();
            this.baseUrlButton = this.Factory.CreateRibbonButton();
            this.importTestcaseButton = this.Factory.CreateRibbonButton();
            this.recodingButton = this.Factory.CreateRibbonToggleButton();
            this.group1 = this.Factory.CreateRibbonGroup();
            this.runButton = this.Factory.CreateRibbonButton();
            this.separator4 = this.Factory.CreateRibbonSeparator();
            this.runOnlyFailedButton = this.Factory.CreateRibbonButton();
            this.runCurrentButton = this.Factory.CreateRibbonButton();
            this.evidenceGroup = this.Factory.CreateRibbonGroup();
            this.failedEvidenceRecordButton = this.Factory.CreateRibbonToggleButton();
            this.passedEvidenceRecordButton = this.Factory.CreateRibbonToggleButton();
            this.deleteAllEvidenceButton = this.Factory.CreateRibbonButton();
            this.separator3 = this.Factory.CreateRibbonSeparator();
            this.nextButton = this.Factory.CreateRibbonButton();
            this.prevButton = this.Factory.CreateRibbonButton();
            this.browserGroup = this.Factory.CreateRibbonGroup();
            this.ieButton = this.Factory.CreateRibbonToggleButton();
            this.firefoxButton = this.Factory.CreateRibbonToggleButton();
            this.chromeButton = this.Factory.CreateRibbonToggleButton();
            this.helpGroup = this.Factory.CreateRibbonGroup();
            this.helpButton = this.Factory.CreateRibbonToggleButton();
            this.showVersionButton = this.Factory.CreateRibbonButton();
            this.debugGroup = this.Factory.CreateRibbonGroup();
            this.button1 = this.Factory.CreateRibbonButton();
            this.button2 = this.Factory.CreateRibbonButton();
            this.button3 = this.Factory.CreateRibbonButton();
            this.notifyIcon1 = new System.Windows.Forms.NotifyIcon(this.components);
            this.group2 = this.Factory.CreateRibbonGroup();
            this.tab1.SuspendLayout();
            this.mainGroup.SuspendLayout();
            this.group1.SuspendLayout();
            this.evidenceGroup.SuspendLayout();
            this.browserGroup.SuspendLayout();
            this.helpGroup.SuspendLayout();
            this.debugGroup.SuspendLayout();
            this.group2.SuspendLayout();
            // 
            // tab1
            // 
            this.tab1.Groups.Add(this.mainGroup);
            this.tab1.Groups.Add(this.group2);
            this.tab1.Groups.Add(this.group1);
            this.tab1.Groups.Add(this.evidenceGroup);
            this.tab1.Groups.Add(this.browserGroup);
            this.tab1.Groups.Add(this.helpGroup);
            this.tab1.Groups.Add(this.debugGroup);
            this.tab1.Label = "Selenium";
            this.tab1.Name = "tab1";
            // 
            // mainGroup
            // 
            this.mainGroup.Items.Add(this.createScenarioButton);
            this.mainGroup.Items.Add(this.createTestDataButton);
            this.mainGroup.Items.Add(this.toggleListPaneVisibleButton);
            this.mainGroup.Items.Add(this.baseUrlButton);
            this.mainGroup.Items.Add(this.importTestcaseButton);
            this.mainGroup.Label = "TestCase";
            this.mainGroup.Name = "mainGroup";
            // 
            // toggleListPaneVisibleButton
            // 
            this.toggleListPaneVisibleButton.Image = global::SeleniumExcelAddIn.Properties.Resources.application_side_list;
            this.toggleListPaneVisibleButton.Label = "TestCase List";
            this.toggleListPaneVisibleButton.Name = "toggleListPaneVisibleButton";
            this.toggleListPaneVisibleButton.ShowImage = true;
            // 
            // createScenarioButton
            // 
            this.createScenarioButton.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.createScenarioButton.Image = global::SeleniumExcelAddIn.Properties.Resources.table_lightning32;
            this.createScenarioButton.Label = "New TestCase";
            this.createScenarioButton.Name = "createScenarioButton";
            this.createScenarioButton.ShowImage = true;
            // 
            // createTestDataButton
            // 
            this.createTestDataButton.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.createTestDataButton.Image = global::SeleniumExcelAddIn.Properties.Resources.database_lightning1;
            this.createTestDataButton.Label = "New TestData";
            this.createTestDataButton.Name = "createTestDataButton";
            this.createTestDataButton.ShowImage = true;
            // 
            // syntaxCheckButton
            // 
            this.syntaxCheckButton.Image = global::SeleniumExcelAddIn.Properties.Resources.spellcheck_error;
            this.syntaxCheckButton.Label = "Syntax Check";
            this.syntaxCheckButton.Name = "syntaxCheckButton";
            this.syntaxCheckButton.ShowImage = true;
            // 
            // baseUrlButton
            // 
            this.baseUrlButton.Image = global::SeleniumExcelAddIn.Properties.Resources.web_layout;
            this.baseUrlButton.Label = "BaseURL";
            this.baseUrlButton.Name = "baseUrlButton";
            this.baseUrlButton.ShowImage = true;
            // 
            // importTestcaseButton
            // 
            this.importTestcaseButton.Image = global::SeleniumExcelAddIn.Properties.Resources.text_imports;
            this.importTestcaseButton.Label = "Import from IDE";
            this.importTestcaseButton.Name = "importTestcaseButton";
            this.importTestcaseButton.ShowImage = true;
            this.importTestcaseButton.SuperTip = "Import Selenium IDE Testcase";
            // 
            // recodingButton
            // 
            this.recodingButton.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.recodingButton.Label = "Recoding";
            this.recodingButton.Name = "recodingButton";
            this.recodingButton.ShowImage = true;
            // 
            // group1
            // 
            this.group1.Items.Add(this.runButton);
            this.group1.Items.Add(this.separator4);
            this.group1.Items.Add(this.runOnlyFailedButton);
            this.group1.Items.Add(this.runCurrentButton);
            this.group1.Items.Add(this.syntaxCheckButton);
            this.group1.Label = "Run";
            this.group1.Name = "group1";
            // 
            // runButton
            // 
            this.runButton.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.runButton.Image = global::SeleniumExcelAddIn.Properties.Resources.control_play_blue32;
            this.runButton.Label = "Run All";
            this.runButton.Name = "runButton";
            this.runButton.ShowImage = true;
            // 
            // separator4
            // 
            this.separator4.Name = "separator4";
            // 
            // runOnlyFailedButton
            // 
            this.runOnlyFailedButton.Label = "Only Failed";
            this.runOnlyFailedButton.Name = "runOnlyFailedButton";
            // 
            // runCurrentButton
            // 
            this.runCurrentButton.Label = "Current TestCase";
            this.runCurrentButton.Name = "runCurrentButton";
            // 
            // evidenceGroup
            // 
            this.evidenceGroup.Items.Add(this.failedEvidenceRecordButton);
            this.evidenceGroup.Items.Add(this.passedEvidenceRecordButton);
            this.evidenceGroup.Items.Add(this.deleteAllEvidenceButton);
            this.evidenceGroup.Items.Add(this.separator3);
            this.evidenceGroup.Items.Add(this.nextButton);
            this.evidenceGroup.Items.Add(this.prevButton);
            this.evidenceGroup.Label = "Evidence";
            this.evidenceGroup.Name = "evidenceGroup";
            // 
            // failedEvidenceRecordButton
            // 
            this.failedEvidenceRecordButton.Image = global::SeleniumExcelAddIn.Properties.Resources.camera_delete;
            this.failedEvidenceRecordButton.Label = "Failed";
            this.failedEvidenceRecordButton.Name = "failedEvidenceRecordButton";
            this.failedEvidenceRecordButton.ShowImage = true;
            this.failedEvidenceRecordButton.SuperTip = "automatic recording evidence of Failed";
            // 
            // passedEvidenceRecordButton
            // 
            this.passedEvidenceRecordButton.Image = global::SeleniumExcelAddIn.Properties.Resources.camera_add;
            this.passedEvidenceRecordButton.Label = "Passed";
            this.passedEvidenceRecordButton.Name = "passedEvidenceRecordButton";
            this.passedEvidenceRecordButton.ShowImage = true;
            this.passedEvidenceRecordButton.SuperTip = "automatic recording evidence of Passed";
            // 
            // deleteAllEvidenceButton
            // 
            this.deleteAllEvidenceButton.Image = global::SeleniumExcelAddIn.Properties.Resources.bin_closed;
            this.deleteAllEvidenceButton.Label = "Delete All";
            this.deleteAllEvidenceButton.Name = "deleteAllEvidenceButton";
            this.deleteAllEvidenceButton.ShowImage = true;
            // 
            // separator3
            // 
            this.separator3.Name = "separator3";
            // 
            // nextButton
            // 
            this.nextButton.Image = global::SeleniumExcelAddIn.Properties.Resources.resultset_next;
            this.nextButton.Label = "Next";
            this.nextButton.Name = "nextButton";
            this.nextButton.ShowImage = true;
            // 
            // prevButton
            // 
            this.prevButton.Image = global::SeleniumExcelAddIn.Properties.Resources.resultset_previous;
            this.prevButton.Label = "Previous";
            this.prevButton.Name = "prevButton";
            this.prevButton.ShowImage = true;
            // 
            // browserGroup
            // 
            this.browserGroup.Items.Add(this.ieButton);
            this.browserGroup.Items.Add(this.firefoxButton);
            this.browserGroup.Items.Add(this.chromeButton);
            this.browserGroup.Label = "WebDriver";
            this.browserGroup.Name = "browserGroup";
            // 
            // ieButton
            // 
            this.ieButton.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.ieButton.Image = global::SeleniumExcelAddIn.Properties.Resources.iexplore_9;
            this.ieButton.Label = "Internet Explorer";
            this.ieButton.Name = "ieButton";
            this.ieButton.ShowImage = true;
            // 
            // firefoxButton
            // 
            this.firefoxButton.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.firefoxButton.Image = global::SeleniumExcelAddIn.Properties.Resources.firefox;
            this.firefoxButton.Label = "Firefox";
            this.firefoxButton.Name = "firefoxButton";
            this.firefoxButton.ShowImage = true;
            // 
            // chromeButton
            // 
            this.chromeButton.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge;
            this.chromeButton.Image = global::SeleniumExcelAddIn.Properties.Resources.chrome;
            this.chromeButton.Label = "Chrome";
            this.chromeButton.Name = "chromeButton";
            this.chromeButton.ShowImage = true;
            // 
            // helpGroup
            // 
            this.helpGroup.Items.Add(this.helpButton);
            this.helpGroup.Items.Add(this.showVersionButton);
            this.helpGroup.Label = "Help";
            this.helpGroup.Name = "helpGroup";
            // 
            // helpButton
            // 
            this.helpButton.Image = global::SeleniumExcelAddIn.Properties.Resources.help;
            this.helpButton.Label = "Reference";
            this.helpButton.Name = "helpButton";
            this.helpButton.ScreenTip = "Selenium Command Reference";
            this.helpButton.ShowImage = true;
            // 
            // showVersionButton
            // 
            this.showVersionButton.Image = global::SeleniumExcelAddIn.Properties.Resources.cricket;
            this.showVersionButton.Label = "Version";
            this.showVersionButton.Name = "showVersionButton";
            this.showVersionButton.ShowImage = true;
            // 
            // debugGroup
            // 
            this.debugGroup.Items.Add(this.button1);
            this.debugGroup.Items.Add(this.button2);
            this.debugGroup.Items.Add(this.button3);
            this.debugGroup.Label = "Debug";
            this.debugGroup.Name = "debugGroup";
            // 
            // button1
            // 
            this.button1.Label = "en-us";
            this.button1.Name = "button1";
            this.button1.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.Label = "ja-jp";
            this.button2.Name = "button2";
            this.button2.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.Label = "save command list";
            this.button3.Name = "button3";
            this.button3.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.button3_Click);
            // 
            // notifyIcon1
            // 
            this.notifyIcon1.Text = "notifyIcon1";
            this.notifyIcon1.Visible = true;
            // 
            // group2
            // 
            this.group2.Items.Add(this.recodingButton);
            this.group2.Label = "Recording";
            this.group2.Name = "group2";
            // 
            // Ribbon1
            // 
            this.Name = "Ribbon1";
            this.RibbonType = "Microsoft.Excel.Workbook";
            this.Tabs.Add(this.tab1);
            this.Load += new Microsoft.Office.Tools.Ribbon.RibbonUIEventHandler(this.Ribbon1_Load);
            this.tab1.ResumeLayout(false);
            this.tab1.PerformLayout();
            this.mainGroup.ResumeLayout(false);
            this.mainGroup.PerformLayout();
            this.group1.ResumeLayout(false);
            this.group1.PerformLayout();
            this.evidenceGroup.ResumeLayout(false);
            this.evidenceGroup.PerformLayout();
            this.browserGroup.ResumeLayout(false);
            this.browserGroup.PerformLayout();
            this.helpGroup.ResumeLayout(false);
            this.helpGroup.PerformLayout();
            this.debugGroup.ResumeLayout(false);
            this.debugGroup.PerformLayout();
            this.group2.ResumeLayout(false);
            this.group2.PerformLayout();

        }

        #endregion

        internal Microsoft.Office.Tools.Ribbon.RibbonTab tab1;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton toggleListPaneVisibleButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton createScenarioButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton createTestDataButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup helpGroup;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton showVersionButton;
        private System.Windows.Forms.NotifyIcon notifyIcon1;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup debugGroup;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton button1;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton button2;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup browserGroup;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton ieButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton firefoxButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton chromeButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup mainGroup;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup evidenceGroup;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton deleteAllEvidenceButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton prevButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton nextButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonSeparator separator3;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton failedEvidenceRecordButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton runCurrentButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton baseUrlButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton importTestcaseButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton button3;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup group1;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton runButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton runOnlyFailedButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton syntaxCheckButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonSeparator separator4;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton passedEvidenceRecordButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton helpButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonToggleButton recodingButton;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup group2;
    }

    partial class ThisRibbonCollection
    {
        internal Ribbon1 Ribbon1
        {
            get { return this.GetRibbon<Ribbon1>(); }
        }
    }
}
