//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumExcelAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumExcelAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Delete All Evidence ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Action_DeleteEvidenceAll_Confirm {
            get {
                return ResourceManager.GetString("Action_DeleteEvidenceAll_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Action_Run_Failed {
            get {
                return ResourceManager.GetString("Action_Run_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined Action = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionManager_GetActionId_Error {
            get {
                return ResourceManager.GetString("ActionManager_GetActionId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Scenario(ListObject) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionValidator_NoSuchListObject {
            get {
                return ResourceManager.GetString("ActionValidator_NoSuchListObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Test Scenarios. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionValidator_NoSuchWorksheetContext {
            get {
                return ResourceManager.GetString("ActionValidator_NoSuchWorksheetContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Data Body. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionValidator_NotListObjectDataBody {
            get {
                return ResourceManager.GetString("ActionValidator_NotListObjectDataBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workbook is Protectedted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionValidator_WorkbookEditable {
            get {
                return ResourceManager.GetString("ActionValidator_WorkbookEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workbook Not Opened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionValidator_WorkbookNotPresent {
            get {
                return ResourceManager.GetString("ActionValidator_WorkbookNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workbook is Read-Only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionValidator_WorkbookReadonly {
            get {
                return ResourceManager.GetString("ActionValidator_WorkbookReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Worksheet Not Opened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ActionValidator_WorksheetNotPresent {
            get {
                return ResourceManager.GetString("ActionValidator_WorksheetNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already Exists Scenario. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlreadyExistsListObject {
            get {
                return ResourceManager.GetString("AlreadyExistsListObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon app_icon {
            get {
                object obj = ResourceManager.GetObject("app_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   SeleniumExcelAddIn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppDir {
            get {
                return ResourceManager.GetString("AppDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap application_side_list {
            get {
                object obj = ResourceManager.GetObject("application_side_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Selenium Excel AddIn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Assertion Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssertError {
            get {
                return ResourceManager.GetString("AssertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected = &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssertExpected {
            get {
                return ResourceManager.GetString("AssertExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected = &quot;{0}&quot;, Actual = &quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssertExpectedAndActual {
            get {
                return ResourceManager.GetString("AssertExpectedAndActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BaseUrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Url に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseUrlInvalid {
            get {
                return ResourceManager.GetString("BaseUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap bin_closed {
            get {
                object obj = ResourceManager.GetObject("bin_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap blank16 {
            get {
                object obj = ResourceManager.GetObject("blank16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap book {
            get {
                object obj = ResourceManager.GetObject("book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap bullet_yellow {
            get {
                object obj = ResourceManager.GetObject("bullet_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap camera_add {
            get {
                object obj = ResourceManager.GetObject("camera_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap camera_delete {
            get {
                object obj = ResourceManager.GetObject("camera_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   TestRunning Cancel ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelTestRun {
            get {
                return ResourceManager.GetString("CancelTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap check_boxes {
            get {
                object obj = ResourceManager.GetObject("check_boxes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   New version {0} released.
        ///Click here to download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckNewVersion1 {
            get {
                return ResourceManager.GetString("CheckNewVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap chrome {
            get {
                object obj = ResourceManager.GetObject("chrome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] chromedriver {
            get {
                object obj = ResourceManager.GetObject("chromedriver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Command is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandNameIsEmpty {
            get {
                return ResourceManager.GetString("CommandNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Command Compile Errors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompilerError {
            get {
                return ResourceManager.GetString("CompilerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap control_cursor_blue {
            get {
                object obj = ResourceManager.GetObject("control_cursor_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap control_end_blue {
            get {
                object obj = ResourceManager.GetObject("control_end_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap control_play_blue {
            get {
                object obj = ResourceManager.GetObject("control_play_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap control_play_blue32 {
            get {
                object obj = ResourceManager.GetObject("control_play_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cricket {
            get {
                object obj = ResourceManager.GetObject("cricket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap database_lightning {
            get {
                object obj = ResourceManager.GetObject("database_lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap database_lightning1 {
            get {
                object obj = ResourceManager.GetObject("database_lightning1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Evidence_Browser {
            get {
                return ResourceManager.GetString("Evidence_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Evidence_Command {
            get {
                return ResourceManager.GetString("Evidence_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ErrorMessage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Evidence_ErrorMessage {
            get {
                return ResourceManager.GetString("Evidence_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestScenario に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Evidence_Scenario {
            get {
                return ResourceManager.GetString("Evidence_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Evidence_Time {
            get {
                return ResourceManager.GetString("Evidence_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PageTitle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Evidence_Title {
            get {
                return ResourceManager.GetString("Evidence_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Url に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Evidence_Url {
            get {
                return ResourceManager.GetString("Evidence_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evidence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EviPane_Title {
            get {
                return ResourceManager.GetString("EviPane_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap firefox {
            get {
                object obj = ResourceManager.GetObject("firefox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Selenium Reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpPaneTitle {
            get {
                return ResourceManager.GetString("HelpPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://selenium-excel-addin.jpn.org/en/commands.html?addin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://selenium-excel-addin.jpn.org に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] IEDriverServer {
            get {
                object obj = ResourceManager.GetObject("IEDriverServer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap iexplore_9 {
            get {
                object obj = ResourceManager.GetObject("iexplore_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Import Selenium IDE Testcase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportTestcaseDialogTitle {
            get {
                return ResourceManager.GetString("ImportTestcaseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file is not TestCase of Selenium IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportTestcaseNoSuchProfile {
            get {
                return ResourceManager.GetString("ImportTestcaseNoSuchProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap insert_citation {
            get {
                object obj = ResourceManager.GetObject("insert_citation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap insert_citation1 {
            get {
                object obj = ResourceManager.GetObject("insert_citation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Invalid Attribute Locator. (e.g &quot;element@attr&quot;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvaildAttributeLocator {
            get {
                return ResourceManager.GetString("InvaildAttributeLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap link_break {
            get {
                object obj = ResourceManager.GetObject("link_break", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListColumnName_Command {
            get {
                return ResourceManager.GetString("ListColumnName_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListColumnName_ErrorMessage {
            get {
                return ResourceManager.GetString("ListColumnName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evidence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListColumnName_Evidence {
            get {
                return ResourceManager.GetString("ListColumnName_Evidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListColumnName_Result {
            get {
                return ResourceManager.GetString("ListColumnName_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListColumnName_Target {
            get {
                return ResourceManager.GetString("ListColumnName_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListColumnName_Value {
            get {
                return ResourceManager.GetString("ListColumnName_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestCase List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListPane_Title {
            get {
                return ResourceManager.GetString("ListPane_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListPaneStatusBar_ErrorFormat {
            get {
                return ResourceManager.GetString("ListPaneStatusBar_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListPaneStatusBar_SuccessFormat {
            get {
                return ResourceManager.GetString("ListPaneStatusBar_SuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- [log4net.config] --&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot;
        ///             type=&quot;log4net.Config.Log4NetConfigurationSectionHandler, log4net&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;appSettings&gt;
        ///    &lt;!--
        ///    &lt;add key=&quot;log4net.Internal.Debug&quot;
        ///         value=&quot;true&quot; /&gt;
        ///         --&gt;
        ///  &lt;/appSettings&gt;
        ///
        ///  &lt;log4net&gt;
        ///
        ///    &lt;appender name=&quot;DebugConsole&quot;
        ///              type=&quot;log4net.Appender.DebugAppender&quot;&gt;
        ///      &lt;immediateFlush value=&quot;true&quot; /&gt;
        ///    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string log4net_debug {
            get {
                return ResourceManager.GetString("log4net_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- [log4net.config] --&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot;
        ///             type=&quot;log4net.Config.Log4NetConfigurationSectionHandler, log4net&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;appSettings&gt;
        ///    &lt;!--
        ///    &lt;add key=&quot;log4net.Internal.Debug&quot;
        ///         value=&quot;true&quot; /&gt;
        ///         --&gt;
        ///  &lt;/appSettings&gt;
        ///
        ///  &lt;log4net&gt;
        ///
        ///    &lt;appender name=&quot;DebugConsole&quot;
        ///              type=&quot;log4net.Appender.DebugAppender&quot;&gt;
        ///      &lt;immediateFlush value=&quot;true&quot; /&gt;
        ///    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string log4net_release {
            get {
                return ResourceManager.GetString("log4net_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Alert Dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSuchAlert {
            get {
                return ResourceManager.GetString("NoSuchAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSuchCommand {
            get {
                return ResourceManager.GetString("NoSuchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Cookie =&quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSuchCookie {
            get {
                return ResourceManager.GetString("NoSuchCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Data Column Name = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSuchDataName {
            get {
                return ResourceManager.GetString("NoSuchDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option element ID specified by &quot;{0}&quot; does not exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSuchSelectById {
            get {
                return ResourceManager.GetString("NoSuchSelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Variable = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSuchVar {
            get {
                return ResourceManager.GetString("NoSuchVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Installed {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotInstalledWebBrowser {
            get {
                return ResourceManager.GetString("NotInstalledWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap page_white_code {
            get {
                object obj = ResourceManager.GetObject("page_white_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap page_world {
            get {
                object obj = ResourceManager.GetObject("page_world", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   specifies the x,y position (i.e. &quot;-10,20&quot;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParseCoordStringError {
            get {
                return ResourceManager.GetString("ParseCoordStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause up to 60 minutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PauseTimeOver {
            get {
                return ResourceManager.GetString("PauseTimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestData_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prefix_Data {
            get {
                return ResourceManager.GetString("Prefix_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evidence_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prefix_Evidence {
            get {
                return ResourceManager.GetString("Prefix_Evidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestResult に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prefix_Result {
            get {
                return ResourceManager.GetString("Prefix_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestCase_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prefix_Scenario {
            get {
                return ResourceManager.GetString("Prefix_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining Time: {0} Days {1} Hours. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_Days {
            get {
                return ResourceManager.GetString("Progress_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining Time: {0} Hours {1} Minutes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_Hours {
            get {
                return ResourceManager.GetString("Progress_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steps: {0} / {1} (Failed: {2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_Info {
            get {
                return ResourceManager.GetString("Progress_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining Time: {0} Minutes {1} Seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_Mins {
            get {
                return ResourceManager.GetString("Progress_Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining Time: {0} Seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_Secs {
            get {
                return ResourceManager.GetString("Progress_Secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Such Element ={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Recorder_NoSuchElement {
            get {
                return ResourceManager.GetString("Recorder_NoSuchElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportColumnResult {
            get {
                return ResourceManager.GetString("ReportColumnResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportColumnTestCase {
            get {
                return ResourceManager.GetString("ReportColumnTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportColumnTestData {
            get {
                return ResourceManager.GetString("ReportColumnTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap resultset_next {
            get {
                object obj = ResourceManager.GetObject("resultset_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap resultset_previous {
            get {
                object obj = ResourceManager.GetObject("resultset_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   TestCase is not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScenarioIsNotSelected {
            get {
                return ResourceManager.GetString("ScenarioIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;title&gt;Selenium Reference&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Selenium Reference&lt;/h1&gt;
        ///&lt;ol&gt;
        ///&lt;li&gt;
        ///&lt;a href=&quot;#name&quot;&gt;Concepts&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;ol&gt;
        ///&lt;li&gt;
        ///&lt;a href=&quot;#locators&quot;&gt;Element Locators&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;a href=&quot;#element-filters&quot;&gt;Element Filters&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;a href=&quot;#patterns&quot;&gt;String-match Patterns&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ol&gt;
        ///&lt;li&gt;
        ///&lt;a href=&quot;#actions&quot;&gt;Selenium Actions&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;a href=&quot;#accessors&quot;&gt;Selenium Accessors&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;a href=&quot;#paramete [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string selenium_reference {
            get {
                return ResourceManager.GetString("selenium_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap spellcheck {
            get {
                object obj = ResourceManager.GetObject("spellcheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap spellcheck_error {
            get {
                object obj = ResourceManager.GetObject("spellcheck_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Syntax Check {0} Failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxCheckFailed {
            get {
                return ResourceManager.GetString("SyntaxCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syntax Check Successed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxCheckSuccess {
            get {
                return ResourceManager.GetString("SyntaxCheckSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap table_lightning {
            get {
                object obj = ResourceManager.GetObject("table_lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap table_lightning32 {
            get {
                object obj = ResourceManager.GetObject("table_lightning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap table_link {
            get {
                object obj = ResourceManager.GetObject("table_link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Target Required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestCommand_Validate_RequireTarget {
            get {
                return ResourceManager.GetString("TestCommand_Validate_RequireTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value Required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestCommand_Validate_RequireValue {
            get {
                return ResourceManager.GetString("TestCommand_Validate_RequireValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (None) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestDataMenuItem_Text {
            get {
                return ResourceManager.GetString("TestDataMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestIsEmpty {
            get {
                return ResourceManager.GetString("TestIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestResult_Failed {
            get {
                return ResourceManager.GetString("TestResult_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestResult_None {
            get {
                return ResourceManager.GetString("TestResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestResult_Passed {
            get {
                return ResourceManager.GetString("TestResult_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   skipped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestResult_Skipped {
            get {
                return ResourceManager.GetString("TestResult_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already Test Running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TestRunner_AlreadyRunning {
            get {
                return ResourceManager.GetString("TestRunner_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap text_imports {
            get {
                object obj = ResourceManager.GetObject("text_imports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Verify Failed. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VerifyFailed {
            get {
                return ResourceManager.GetString("VerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap web_layout {
            get {
                object obj = ResourceManager.GetObject("web_layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Not Supported WebDriver Type = &quot;{0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebDriverFactory_NotSupportedDriverType {
            get {
                return ResourceManager.GetString("WebDriverFactory_NotSupportedDriverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap world_go {
            get {
                object obj = ResourceManager.GetObject("world_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
