// <auto-generated />
namespace SeleniumExcelAddIn.View
{
    partial class ListPaneControl
    {
        /// <summary> 
        /// 必要なデザイナー変数です。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 使用中のリソースをすべてクリーンアップします。
        /// </summary>
        /// <param testDataWorksheetName="disposing">マネージ リソースが破棄される場合 true、破棄されない場合は false です。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region コンポーネント デザイナーで生成されたコード

        /// <summary> 
        /// デザイナー サポートに必要なメソッドです。このメソッドの内容を 
        /// コード エディターで変更しないでください。
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ListPaneControl));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.successStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.errorStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.refreshButton = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            this.importButton = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.createScenarioButton = new System.Windows.Forms.ToolStripButton();
            this.createTestDataButton = new System.Windows.Forms.ToolStripButton();
            this.toolStripDropDownButton1 = new System.Windows.Forms.ToolStripDropDownButton();
            this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.noneToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.scenarioCheckedToggleButton = new System.Windows.Forms.ToolStripSplitButton();
            this.scenarioCheckedAllMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.scenarioUncheckedallMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.runButton = new System.Windows.Forms.ToolStripSplitButton();
            this.runCurrentMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.runOnlyFailedMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.checkedColumn = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.statucIconColumn = new System.Windows.Forms.DataGridViewImageColumn();
            this.iconColumn = new System.Windows.Forms.DataGridViewImageColumn();
            this.testCaseColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.testDataColumn = new System.Windows.Forms.DataGridViewLinkColumn();
            this.statusStrip1.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.contextMenuStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // statusStrip1
            // 
            resources.ApplyResources(this.statusStrip1, "statusStrip1");
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.successStatusLabel,
            this.errorStatusLabel});
            this.statusStrip1.Name = "statusStrip1";
            // 
            // successStatusLabel
            // 
            resources.ApplyResources(this.successStatusLabel, "successStatusLabel");
            this.successStatusLabel.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right;
            this.successStatusLabel.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.successStatusLabel.Name = "successStatusLabel";
            // 
            // errorStatusLabel
            // 
            resources.ApplyResources(this.errorStatusLabel, "errorStatusLabel");
            this.errorStatusLabel.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right;
            this.errorStatusLabel.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.errorStatusLabel.Name = "errorStatusLabel";
            // 
            // toolStrip1
            // 
            resources.ApplyResources(this.toolStrip1, "toolStrip1");
            this.toolStrip1.GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden;
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.refreshButton,
            this.toolStripSeparator3,
            this.importButton,
            this.toolStripSeparator2,
            this.createScenarioButton,
            this.createTestDataButton,
            this.toolStripDropDownButton1,
            this.toolStripSeparator1,
            this.scenarioCheckedToggleButton,
            this.runButton});
            this.toolStrip1.Name = "toolStrip1";
            // 
            // refreshButton
            // 
            resources.ApplyResources(this.refreshButton, "refreshButton");
            this.refreshButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.refreshButton.Image = global::SeleniumExcelAddIn.Properties.Resources.arrow_refresh;
            this.refreshButton.Name = "refreshButton";
            // 
            // toolStripSeparator3
            // 
            resources.ApplyResources(this.toolStripSeparator3, "toolStripSeparator3");
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            // 
            // importButton
            // 
            resources.ApplyResources(this.importButton, "importButton");
            this.importButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.importButton.Image = global::SeleniumExcelAddIn.Properties.Resources.text_imports;
            this.importButton.Name = "importButton";
            // 
            // toolStripSeparator2
            // 
            resources.ApplyResources(this.toolStripSeparator2, "toolStripSeparator2");
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            // 
            // createScenarioButton
            // 
            resources.ApplyResources(this.createScenarioButton, "createScenarioButton");
            this.createScenarioButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.createScenarioButton.Image = global::SeleniumExcelAddIn.Properties.Resources.table_lightning;
            this.createScenarioButton.Name = "createScenarioButton";
            // 
            // createTestDataButton
            // 
            resources.ApplyResources(this.createTestDataButton, "createTestDataButton");
            this.createTestDataButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.createTestDataButton.Image = global::SeleniumExcelAddIn.Properties.Resources.database_lightning;
            this.createTestDataButton.Name = "createTestDataButton";
            // 
            // toolStripDropDownButton1
            // 
            resources.ApplyResources(this.toolStripDropDownButton1, "toolStripDropDownButton1");
            this.toolStripDropDownButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripDropDownButton1.DropDown = this.contextMenuStrip1;
            this.toolStripDropDownButton1.Image = global::SeleniumExcelAddIn.Properties.Resources.link;
            this.toolStripDropDownButton1.Name = "toolStripDropDownButton1";
            // 
            // contextMenuStrip1
            // 
            resources.ApplyResources(this.contextMenuStrip1, "contextMenuStrip1");
            this.contextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.noneToolStripMenuItem});
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.OwnerItem = this.toolStripDropDownButton1;
            this.contextMenuStrip1.Opening += new System.ComponentModel.CancelEventHandler(this.contextMenuStrip1_Opening);
            // 
            // noneToolStripMenuItem
            // 
            resources.ApplyResources(this.noneToolStripMenuItem, "noneToolStripMenuItem");
            this.noneToolStripMenuItem.Name = "noneToolStripMenuItem";
            // 
            // toolStripSeparator1
            // 
            resources.ApplyResources(this.toolStripSeparator1, "toolStripSeparator1");
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            // 
            // scenarioCheckedToggleButton
            // 
            resources.ApplyResources(this.scenarioCheckedToggleButton, "scenarioCheckedToggleButton");
            this.scenarioCheckedToggleButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.scenarioCheckedToggleButton.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.scenarioCheckedAllMenuItem,
            this.scenarioUncheckedallMenuItem});
            this.scenarioCheckedToggleButton.Image = global::SeleniumExcelAddIn.Properties.Resources.check_boxes;
            this.scenarioCheckedToggleButton.Name = "scenarioCheckedToggleButton";
            // 
            // scenarioCheckedAllMenuItem
            // 
            resources.ApplyResources(this.scenarioCheckedAllMenuItem, "scenarioCheckedAllMenuItem");
            this.scenarioCheckedAllMenuItem.Name = "scenarioCheckedAllMenuItem";
            // 
            // scenarioUncheckedallMenuItem
            // 
            resources.ApplyResources(this.scenarioUncheckedallMenuItem, "scenarioUncheckedallMenuItem");
            this.scenarioUncheckedallMenuItem.Name = "scenarioUncheckedallMenuItem";
            // 
            // runButton
            // 
            resources.ApplyResources(this.runButton, "runButton");
            this.runButton.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
            this.runButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.runButton.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.runCurrentMenuItem,
            this.runOnlyFailedMenuItem});
            this.runButton.Image = global::SeleniumExcelAddIn.Properties.Resources.control_play_blue;
            this.runButton.Name = "runButton";
            // 
            // runCurrentMenuItem
            // 
            resources.ApplyResources(this.runCurrentMenuItem, "runCurrentMenuItem");
            this.runCurrentMenuItem.Name = "runCurrentMenuItem";
            // 
            // runOnlyFailedMenuItem
            // 
            resources.ApplyResources(this.runOnlyFailedMenuItem, "runOnlyFailedMenuItem");
            this.runOnlyFailedMenuItem.Name = "runOnlyFailedMenuItem";
            // 
            // dataGridView1
            // 
            resources.ApplyResources(this.dataGridView1, "dataGridView1");
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.AllowUserToOrderColumns = true;
            this.dataGridView1.AllowUserToResizeRows = false;
            this.dataGridView1.BackgroundColor = System.Drawing.SystemColors.Window;
            this.dataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Meiryo UI", 9F);
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle1.Padding = new System.Windows.Forms.Padding(2);
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.checkedColumn,
            this.statucIconColumn,
            this.iconColumn,
            this.testCaseColumn,
            this.testDataColumn});
            this.dataGridView1.ContextMenuStrip = this.contextMenuStrip1;
            this.dataGridView1.GridColor = System.Drawing.SystemColors.ControlLight;
            this.dataGridView1.MultiSelect = false;
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.dataGridView1.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.dataGridView1.RowTemplate.Height = 21;
            this.dataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridView1.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_CellContentClick);
            this.dataGridView1.CellPainting += new System.Windows.Forms.DataGridViewCellPaintingEventHandler(this.dataGridView1_CellPainting);
            this.dataGridView1.SelectionChanged += new System.EventHandler(this.dataGridView1_SelectionChanged);
            // 
            // checkedColumn
            // 
            this.checkedColumn.DataPropertyName = "IsChecked";
            resources.ApplyResources(this.checkedColumn, "checkedColumn");
            this.checkedColumn.Name = "checkedColumn";
            this.checkedColumn.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            // 
            // statucIconColumn
            // 
            this.statucIconColumn.DataPropertyName = "StatusIcon";
            resources.ApplyResources(this.statucIconColumn, "statucIconColumn");
            this.statucIconColumn.Name = "statucIconColumn";
            this.statucIconColumn.ReadOnly = true;
            this.statucIconColumn.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            // 
            // iconColumn
            // 
            this.iconColumn.DataPropertyName = "Icon";
            resources.ApplyResources(this.iconColumn, "iconColumn");
            this.iconColumn.Name = "iconColumn";
            this.iconColumn.ReadOnly = true;
            this.iconColumn.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            // 
            // testCaseColumn
            // 
            this.testCaseColumn.DataPropertyName = "DisplayName";
            resources.ApplyResources(this.testCaseColumn, "testCaseColumn");
            this.testCaseColumn.Name = "testCaseColumn";
            this.testCaseColumn.ReadOnly = true;
            this.testCaseColumn.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            // 
            // testDataColumn
            // 
            this.testDataColumn.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.testDataColumn.DataPropertyName = "DataDisplayName";
            resources.ApplyResources(this.testDataColumn, "testDataColumn");
            this.testDataColumn.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.testDataColumn.Name = "testDataColumn";
            this.testDataColumn.ReadOnly = true;
            this.testDataColumn.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            this.testDataColumn.TrackVisitedState = false;
            this.testDataColumn.VisitedLinkColor = System.Drawing.Color.Blue;
            // 
            // ListPaneControl
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.toolStrip1);
            this.Name = "ListPaneControl";
            this.Load += new System.EventHandler(this.PaneControl_Load);
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.contextMenuStrip1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton createScenarioButton;
        private System.Windows.Forms.DataGridView dataGridView1;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip1;
        private System.Windows.Forms.ToolStripButton createTestDataButton;
        private System.Windows.Forms.ToolStripButton refreshButton;
        private System.Windows.Forms.ToolStripMenuItem noneToolStripMenuItem;
        private System.Windows.Forms.ToolStripDropDownButton toolStripDropDownButton1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripSplitButton scenarioCheckedToggleButton;
        private System.Windows.Forms.ToolStripMenuItem scenarioCheckedAllMenuItem;
        private System.Windows.Forms.ToolStripMenuItem scenarioUncheckedallMenuItem;
        private System.Windows.Forms.ToolStripStatusLabel successStatusLabel;
        private System.Windows.Forms.ToolStripStatusLabel errorStatusLabel;
        private System.Windows.Forms.ToolStripSplitButton runButton;
        private System.Windows.Forms.ToolStripMenuItem runCurrentMenuItem;
        private System.Windows.Forms.ToolStripButton importButton;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator3;
        private System.Windows.Forms.ToolStripMenuItem runOnlyFailedMenuItem;
        private System.Windows.Forms.DataGridViewCheckBoxColumn checkedColumn;
        private System.Windows.Forms.DataGridViewImageColumn statucIconColumn;
        private System.Windows.Forms.DataGridViewImageColumn iconColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn testCaseColumn;
        private System.Windows.Forms.DataGridViewLinkColumn testDataColumn;
    }
}
